package org.linlinjava.litemall.db.dao;

import org.linlinjava.litemall.db.domain.Design;
import org.linlinjava.litemall.db.domain.DesignExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DesignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    long countByExample(DesignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int deleteByExample(DesignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int insert(Design record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int insertSelective(Design record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    List<Design> selectByExample(DesignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    Design selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int updateByExampleSelective(@Param("record") Design record, @Param("example") DesignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int updateByExample(@Param("record") Design record, @Param("example") DesignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int updateByPrimaryKeySelective(Design record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int updateByPrimaryKey(Design record);
}
