package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallUserPic;
import org.linlinjava.litemall.db.domain.LitemallUserPicExample;

public interface LitemallUserPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    int insert(LitemallUserPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUserPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    LitemallUserPic selectOneByExample(LitemallUserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    LitemallUserPic selectOneByExampleSelective(@Param("example") LitemallUserPicExample example, @Param("selective") LitemallUserPic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    List<LitemallUserPic> selectByExampleSelective(@Param("example") LitemallUserPicExample example, @Param("selective") LitemallUserPic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    List<LitemallUserPic> selectByExample(LitemallUserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    LitemallUserPic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUserPic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    LitemallUserPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    LitemallUserPic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallUserPic record, @Param("example") LitemallUserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallUserPic record, @Param("example") LitemallUserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUserPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUserPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallUserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_pic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}