package org.linlinjava.litemall.db.dao;

import org.linlinjava.litemall.db.domain.OrderPic;
import org.linlinjava.litemall.db.domain.OrderPicExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    long countByExample(OrderPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int deleteByExample(OrderPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int insert(OrderPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int insertSelective(OrderPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    List<OrderPic> selectByExample(OrderPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    OrderPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int updateByExampleSelective(@Param("record") OrderPic record, @Param("example") OrderPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int updateByExample(@Param("record") OrderPic record, @Param("example") OrderPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int updateByPrimaryKeySelective(OrderPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int updateByPrimaryKey(OrderPic record);
}
