package org.linlinjava.litemall.db.dao;

import org.linlinjava.litemall.db.domain.UserPic;
import org.linlinjava.litemall.db.domain.UserPicExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    long countByExample(UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int deleteByExample(UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int insert(UserPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int insertSelective(UserPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    List<UserPic> selectByExample(UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    UserPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int updateByExampleSelective(@Param("record") UserPic record, @Param("example") UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int updateByExample(@Param("record") UserPic record, @Param("example") UserPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int updateByPrimaryKeySelective(UserPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    int updateByPrimaryKey(UserPic record);
}
