package org.linlinjava.litemall.db.domain;

import java.util.Date;

public class Design {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design.id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design.user_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design.pic_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Integer picId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design.designer_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Integer designerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design.content
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design.status
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design.add_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design.update_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design.deleted
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design.id
     *
     * @return the value of design.id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design.id
     *
     * @param id the value for design.id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design.user_id
     *
     * @return the value of design.user_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design.user_id
     *
     * @param userId the value for design.user_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design.pic_id
     *
     * @return the value of design.pic_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design.pic_id
     *
     * @param picId the value for design.pic_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design.designer_id
     *
     * @return the value of design.designer_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Integer getDesignerId() {
        return designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design.designer_id
     *
     * @param designerId the value for design.designer_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setDesignerId(Integer designerId) {
        this.designerId = designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design.content
     *
     * @return the value of design.content
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design.content
     *
     * @param content the value for design.content
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design.status
     *
     * @return the value of design.status
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design.status
     *
     * @param status the value for design.status
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design.add_time
     *
     * @return the value of design.add_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design.add_time
     *
     * @param addTime the value for design.add_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design.update_time
     *
     * @return the value of design.update_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design.update_time
     *
     * @param updateTime the value for design.update_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design.deleted
     *
     * @return the value of design.deleted
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design.deleted
     *
     * @param deleted the value for design.deleted
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}
