package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class LitemallUserPic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.id
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.key
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.user_id
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.pic_url
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.type
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.add_time
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.update_time
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.deleted
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.id
     *
     * @return the value of user_pic.id
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.id
     *
     * @param id the value for user_pic.id
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.key
     *
     * @return the value of user_pic.key
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.key
     *
     * @param key the value for user_pic.key
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.user_id
     *
     * @return the value of user_pic.user_id
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.user_id
     *
     * @param userId the value for user_pic.user_id
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.pic_url
     *
     * @return the value of user_pic.pic_url
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.pic_url
     *
     * @param picUrl the value for user_pic.pic_url
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.type
     *
     * @return the value of user_pic.type
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.type
     *
     * @param type the value for user_pic.type
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.add_time
     *
     * @return the value of user_pic.add_time
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.add_time
     *
     * @param addTime the value for user_pic.add_time
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.update_time
     *
     * @return the value of user_pic.update_time
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.update_time
     *
     * @param updateTime the value for user_pic.update_time
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.deleted
     *
     * @return the value of user_pic.deleted
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.deleted
     *
     * @param deleted the value for user_pic.deleted
     *
     * @mbg.generated Wed Nov 09 09:22:05 CST 2022
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}
