package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class LitemallOriginalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public LitemallOriginalExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public LitemallOriginalExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public LitemallOriginalExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        LitemallOriginalExample example = new LitemallOriginalExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public LitemallOriginalExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public LitemallOriginalExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOriIdIsNull() {
            addCriterion("ori_id is null");
            return (Criteria) this;
        }

        public Criteria andOriIdIsNotNull() {
            addCriterion("ori_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriIdEqualTo(Integer value) {
            addCriterion("ori_id =", value, "oriId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andOriIdEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("ori_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOriIdNotEqualTo(Integer value) {
            addCriterion("ori_id <>", value, "oriId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andOriIdNotEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("ori_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOriIdGreaterThan(Integer value) {
            addCriterion("ori_id >", value, "oriId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andOriIdGreaterThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("ori_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOriIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ori_id >=", value, "oriId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andOriIdGreaterThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("ori_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOriIdLessThan(Integer value) {
            addCriterion("ori_id <", value, "oriId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andOriIdLessThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("ori_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOriIdLessThanOrEqualTo(Integer value) {
            addCriterion("ori_id <=", value, "oriId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andOriIdLessThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("ori_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOriIdIn(List<Integer> values) {
            addCriterion("ori_id in", values, "oriId");
            return (Criteria) this;
        }

        public Criteria andOriIdNotIn(List<Integer> values) {
            addCriterion("ori_id not in", values, "oriId");
            return (Criteria) this;
        }

        public Criteria andOriIdBetween(Integer value1, Integer value2) {
            addCriterion("ori_id between", value1, value2, "oriId");
            return (Criteria) this;
        }

        public Criteria andOriIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ori_id not between", value1, value2, "oriId");
            return (Criteria) this;
        }

        public Criteria andOriUrlIsNull() {
            addCriterion("ori_url is null");
            return (Criteria) this;
        }

        public Criteria andOriUrlIsNotNull() {
            addCriterion("ori_url is not null");
            return (Criteria) this;
        }

        public Criteria andOriUrlEqualTo(String value) {
            addCriterion("ori_url =", value, "oriUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andOriUrlEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("ori_url = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOriUrlNotEqualTo(String value) {
            addCriterion("ori_url <>", value, "oriUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andOriUrlNotEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("ori_url <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOriUrlGreaterThan(String value) {
            addCriterion("ori_url >", value, "oriUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andOriUrlGreaterThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("ori_url > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOriUrlGreaterThanOrEqualTo(String value) {
            addCriterion("ori_url >=", value, "oriUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andOriUrlGreaterThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("ori_url >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOriUrlLessThan(String value) {
            addCriterion("ori_url <", value, "oriUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andOriUrlLessThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("ori_url < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOriUrlLessThanOrEqualTo(String value) {
            addCriterion("ori_url <=", value, "oriUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andOriUrlLessThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("ori_url <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOriUrlLike(String value) {
            addCriterion("ori_url like", value, "oriUrl");
            return (Criteria) this;
        }

        public Criteria andOriUrlNotLike(String value) {
            addCriterion("ori_url not like", value, "oriUrl");
            return (Criteria) this;
        }

        public Criteria andOriUrlIn(List<String> values) {
            addCriterion("ori_url in", values, "oriUrl");
            return (Criteria) this;
        }

        public Criteria andOriUrlNotIn(List<String> values) {
            addCriterion("ori_url not in", values, "oriUrl");
            return (Criteria) this;
        }

        public Criteria andOriUrlBetween(String value1, String value2) {
            addCriterion("ori_url between", value1, value2, "oriUrl");
            return (Criteria) this;
        }

        public Criteria andOriUrlNotBetween(String value1, String value2) {
            addCriterion("ori_url not between", value1, value2, "oriUrl");
            return (Criteria) this;
        }

        public Criteria andDesIdIsNull() {
            addCriterion("des_id is null");
            return (Criteria) this;
        }

        public Criteria andDesIdIsNotNull() {
            addCriterion("des_id is not null");
            return (Criteria) this;
        }

        public Criteria andDesIdEqualTo(Integer value) {
            addCriterion("des_id =", value, "desId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDesIdEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("des_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDesIdNotEqualTo(Integer value) {
            addCriterion("des_id <>", value, "desId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDesIdNotEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("des_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDesIdGreaterThan(Integer value) {
            addCriterion("des_id >", value, "desId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDesIdGreaterThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("des_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDesIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("des_id >=", value, "desId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDesIdGreaterThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("des_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDesIdLessThan(Integer value) {
            addCriterion("des_id <", value, "desId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDesIdLessThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("des_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDesIdLessThanOrEqualTo(Integer value) {
            addCriterion("des_id <=", value, "desId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDesIdLessThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("des_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDesIdIn(List<Integer> values) {
            addCriterion("des_id in", values, "desId");
            return (Criteria) this;
        }

        public Criteria andDesIdNotIn(List<Integer> values) {
            addCriterion("des_id not in", values, "desId");
            return (Criteria) this;
        }

        public Criteria andDesIdBetween(Integer value1, Integer value2) {
            addCriterion("des_id between", value1, value2, "desId");
            return (Criteria) this;
        }

        public Criteria andDesIdNotBetween(Integer value1, Integer value2) {
            addCriterion("des_id not between", value1, value2, "desId");
            return (Criteria) this;
        }

        public Criteria andDesUrlIsNull() {
            addCriterion("des_url is null");
            return (Criteria) this;
        }

        public Criteria andDesUrlIsNotNull() {
            addCriterion("des_url is not null");
            return (Criteria) this;
        }

        public Criteria andDesUrlEqualTo(String value) {
            addCriterion("des_url =", value, "desUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDesUrlEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("des_url = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDesUrlNotEqualTo(String value) {
            addCriterion("des_url <>", value, "desUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDesUrlNotEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("des_url <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDesUrlGreaterThan(String value) {
            addCriterion("des_url >", value, "desUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDesUrlGreaterThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("des_url > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDesUrlGreaterThanOrEqualTo(String value) {
            addCriterion("des_url >=", value, "desUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDesUrlGreaterThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("des_url >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDesUrlLessThan(String value) {
            addCriterion("des_url <", value, "desUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDesUrlLessThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("des_url < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDesUrlLessThanOrEqualTo(String value) {
            addCriterion("des_url <=", value, "desUrl");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDesUrlLessThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("des_url <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDesUrlLike(String value) {
            addCriterion("des_url like", value, "desUrl");
            return (Criteria) this;
        }

        public Criteria andDesUrlNotLike(String value) {
            addCriterion("des_url not like", value, "desUrl");
            return (Criteria) this;
        }

        public Criteria andDesUrlIn(List<String> values) {
            addCriterion("des_url in", values, "desUrl");
            return (Criteria) this;
        }

        public Criteria andDesUrlNotIn(List<String> values) {
            addCriterion("des_url not in", values, "desUrl");
            return (Criteria) this;
        }

        public Criteria andDesUrlBetween(String value1, String value2) {
            addCriterion("des_url between", value1, value2, "desUrl");
            return (Criteria) this;
        }

        public Criteria andDesUrlNotBetween(String value1, String value2) {
            addCriterion("des_url not between", value1, value2, "desUrl");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andUserIdEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("user_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andUserIdNotEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("user_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andUserIdGreaterThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("user_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andUserIdGreaterThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("user_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andUserIdLessThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("user_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andUserIdLessThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("user_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(LocalDateTime value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andAddTimeEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("add_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(LocalDateTime value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andAddTimeNotEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("add_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(LocalDateTime value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andAddTimeGreaterThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("add_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andAddTimeGreaterThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("add_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(LocalDateTime value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andAddTimeLessThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("add_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andAddTimeLessThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("add_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<LocalDateTime> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<LocalDateTime> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("update_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeNotEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("update_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("update_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("update_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("update_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("update_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDeletedEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("deleted = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDeletedNotEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("deleted <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("deleted > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("deleted >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("deleted < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanOrEqualToColumn(LitemallOriginal.Column column) {
            addCriterion(new StringBuilder("deleted <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_original
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        private LitemallOriginalExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        protected Criteria(LitemallOriginalExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public LitemallOriginalExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        public Criteria andLogicalDeleted(boolean deleted) {
            return deleted ? andDeletedEqualTo(LitemallOriginal.Deleted.IS_DELETED.value()) : andDeletedNotEqualTo(LitemallOriginal.Deleted.IS_DELETED.value());
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table litemall_original
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_original
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_original
         *
         * @mbg.generated
         */
        void example(org.linlinjava.litemall.db.domain.LitemallOriginalExample example);
    }
}