package org.linlinjava.litemall.db.domain;

import java.util.Date;

public class LitemallPicture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_picture.id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_picture.url
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_picture.type
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_picture.add_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_picture.update_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_picture.deleted
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_picture.id
     *
     * @return the value of litemall_picture.id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_picture.id
     *
     * @param id the value for litemall_picture.id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_picture.url
     *
     * @return the value of litemall_picture.url
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_picture.url
     *
     * @param url the value for litemall_picture.url
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_picture.type
     *
     * @return the value of litemall_picture.type
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_picture.type
     *
     * @param type the value for litemall_picture.type
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_picture.add_time
     *
     * @return the value of litemall_picture.add_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_picture.add_time
     *
     * @param addTime the value for litemall_picture.add_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_picture.update_time
     *
     * @return the value of litemall_picture.update_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_picture.update_time
     *
     * @param updateTime the value for litemall_picture.update_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_picture.deleted
     *
     * @return the value of litemall_picture.deleted
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_picture.deleted
     *
     * @param deleted the value for litemall_picture.deleted
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}
