package org.linlinjava.litemall.db.domain;

import java.util.Date;

public class OrderPic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pic.id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pic.order_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pic.pic_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Integer picId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pic.add_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pic.update_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pic.deleted
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pic.id
     *
     * @return the value of order_pic.id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pic.id
     *
     * @param id the value for order_pic.id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pic.order_id
     *
     * @return the value of order_pic.order_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pic.order_id
     *
     * @param orderId the value for order_pic.order_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pic.pic_id
     *
     * @return the value of order_pic.pic_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pic.pic_id
     *
     * @param picId the value for order_pic.pic_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pic.add_time
     *
     * @return the value of order_pic.add_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pic.add_time
     *
     * @param addTime the value for order_pic.add_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pic.update_time
     *
     * @return the value of order_pic.update_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pic.update_time
     *
     * @param updateTime the value for order_pic.update_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pic.deleted
     *
     * @return the value of order_pic.deleted
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pic.deleted
     *
     * @param deleted the value for order_pic.deleted
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}
