package org.linlinjava.litemall.db.domain;

import java.util.Date;

public class UserPic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.user_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.pic_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Integer picId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.add_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.update_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.deleted
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.id
     *
     * @return the value of user_pic.id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.id
     *
     * @param id the value for user_pic.id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.user_id
     *
     * @return the value of user_pic.user_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.user_id
     *
     * @param userId the value for user_pic.user_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.pic_id
     *
     * @return the value of user_pic.pic_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.pic_id
     *
     * @param picId the value for user_pic.pic_id
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.add_time
     *
     * @return the value of user_pic.add_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.add_time
     *
     * @param addTime the value for user_pic.add_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.update_time
     *
     * @return the value of user_pic.update_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.update_time
     *
     * @param updateTime the value for user_pic.update_time
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.deleted
     *
     * @return the value of user_pic.deleted
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.deleted
     *
     * @param deleted the value for user_pic.deleted
     *
     * @mbg.generated Sat Oct 15 15:29:23 CST 2022
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}
